# Generated by Django 5.1.3 on 2024-12-11 02:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_document_meeting_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_type',
        ),
        migrations.AddField(
            model_name='meeting',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='meeting',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
