# Generated by Django 5.1.3 on 2024-12-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_document_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
