# Generated by Django 5.1.3 on 2024-12-11 06:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_document_file_document_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None),
        ),
    ]
