# Generated by Django 5.1.3 on 2024-12-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_meeting_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='has_attended',
            field=models.BooleanField(default=False),
        ),
    ]
