# Generated by Django 5.1.3 on 2024-12-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_attendance_has_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='has_attended',
            field=models.CharField(choices=[('Chưa điểm danh', 'Chưa điểm danh'), ('Đang điểm danh', 'Đang điểm danh'), ('Đã điểm danh', 'Đã điểm danh')], default='Chưa điểm danh', max_length=20),
        ),
    ]
